
'use client';
import { products } from '@/lib/merchandise';
import { KpiCard } from '@/components/dashboard/kpi-card';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { ChartContainer } from '@/components/ui/chart';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { TrendingDown, TrendingUp, Package, Wallet, DollarSign, BarChart as BarChartIcon } from 'lucide-react';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

const chartConfig = {
  profit: {
    label: "Profit (KES)",
    color: "hsl(var(--chart-1))",
  },
  sales: {
    label: "Sales (Units)",
    color: "hsl(var(--chart-2))",
  }
};

export default function MerchandiseBIDashboardPage() {
    const totalInventoryValue = products.reduce((acc, p) => acc + p.cost * p.stock, 0);
    const totalProfit = products.reduce((acc, p) => acc + (p.price - p.cost) * p.sales, 0);
    const mostProfitable = [...products].sort((a, b) => ((b.price - b.cost) * b.sales) - ((a.price - a.cost) * a.sales))[0];
    const slowMovingProducts = [...products].sort((a,b) => a.sales - b.sales).slice(0, 3);
    
    const profitData = products.map(p => ({
        name: p.name,
        profit: (p.price - p.cost) * p.sales,
    })).sort((a, b) => b.profit - a.profit);

    const salesVelocityData = products.map(p => ({
        name: p.name,
        sales: p.sales,
    })).sort((a,b) => b.sales - a.sales);

    return (
        <div className="space-y-6">
             <div>
                <h1 className="text-2xl font-bold tracking-tight font-headline">Merchandise BI Dashboard</h1>
                <p className="text-muted-foreground">
                    Deep dive into merchandise sales, profit, and inventory performance.
                </p>
            </div>

            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
                <KpiCard
                    title="Total Profit"
                    value={`KES ${totalProfit.toLocaleString()}`}
                    icon={<DollarSign className="size-5 text-muted-foreground" />}
                    description="From all merchandise sales"
                />
                <KpiCard
                    title="Most Profitable Item"
                    value={mostProfitable.name}
                    icon={<TrendingUp className="size-5 text-muted-foreground" />}
                    description={`Generated KES ${((mostProfitable.price - mostProfitable.cost) * mostProfitable.sales).toLocaleString()} in profit`}
                />
                <KpiCard
                    title="Total Inventory Value"
                    value={`KES ${totalInventoryValue.toLocaleString()}`}
                    icon={<Wallet className="size-5 text-muted-foreground" />}
                    description="Value of all items in stock"
                />
                 <KpiCard
                    title="Slowest Moving Item"
                    value={slowMovingProducts[0].name}
                    icon={<TrendingDown className="size-5 text-muted-foreground" />}
                    description={`Only ${slowMovingProducts[0].sales} units sold`}
                />
            </div>
            
             <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <Card>
                    <CardHeader>
                        <CardTitle className="font-headline flex items-center gap-2"><BarChartIcon /> Profit per Item</CardTitle>
                        <CardDescription>Total profit generated by each product.</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <ChartContainer config={chartConfig} className="min-h-[300px] w-full">
                            <ResponsiveContainer width="100%" height={300}>
                                <BarChart data={profitData} layout="vertical" margin={{ right: 20 }}>
                                    <CartesianGrid horizontal={false} />
                                    <XAxis type="number" dataKey="profit" tickFormatter={(value) => `KES ${Number(value) / 1000}k`} />
                                    <YAxis type="category" dataKey="name" tick={{ fontSize: 12 }} width={120} interval={0}/>
                                    <Tooltip
                                        cursor={{ fill: 'hsl(var(--muted))' }}
                                        content={({ active, payload, label }) => {
                                            if (active && payload && payload.length) {
                                                return (
                                                <div className="rounded-lg border bg-background p-2 shadow-sm">
                                                    <p className="font-bold">{label}</p>
                                                    <p>Profit: KES {payload[0].value?.toLocaleString()}</p>
                                                </div>
                                                )
                                            }
                                            return null
                                            }}
                                    />
                                    <Bar dataKey="profit" fill="var(--color-profit)" radius={[0, 4, 4, 0]} />
                                </BarChart>
                            </ResponsiveContainer>
                        </ChartContainer>
                    </CardContent>
                </Card>
                 <Card>
                    <CardHeader>
                        <CardTitle className="font-headline flex items-center gap-2"><TrendingUp /> Sales Velocity</CardTitle>
                        <CardDescription>Units sold for each product (best to worst).</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <ChartContainer config={chartConfig} className="min-h-[300px] w-full">
                            <ResponsiveContainer width="100%" height={300}>
                                <BarChart data={salesVelocityData}>
                                    <CartesianGrid vertical={false} />
                                    <XAxis dataKey="name" tick={{ fontSize: 12 }} interval={0} angle={-45} textAnchor="end" height={80}/>
                                    <YAxis />
                                    <Tooltip
                                        cursor={{ fill: 'hsl(var(--muted))' }}
                                        content={({ active, payload, label }) => {
                                            if (active && payload && payload.length) {
                                                return (
                                                <div className="rounded-lg border bg-background p-2 shadow-sm">
                                                    <p className="font-bold">{label}</p>
                                                    <p>Sales: {payload[0].value} units</p>
                                                </div>
                                                )
                                            }
                                            return null
                                            }}
                                    />
                                    <Bar dataKey="sales" fill="var(--color-sales)" radius={[4, 4, 0, 0]} />
                                </BarChart>
                            </ResponsiveContainer>
                        </ChartContainer>
                    </CardContent>
                </Card>
            </div>
             <Card>
                <CardHeader>
                    <CardTitle className="font-headline flex items-center gap-2"><TrendingDown /> Slow-Moving Products</CardTitle>
                    <CardDescription>These products have the lowest sales and may require marketing focus or discontinuation.</CardDescription>
                </CardHeader>
                <CardContent>
                    <Table>
                        <TableHeader>
                            <TableRow>
                                <TableHead>Product</TableHead>
                                <TableHead className="text-right">Units Sold</TableHead>
                                <TableHead className="text-right">Stock on Hand</TableHead>
                                <TableHead className="text-right">Inventory Value</TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            {slowMovingProducts.map(product => (
                                <TableRow key={product.id}>
                                    <TableCell className="font-medium">{product.name}</TableCell>
                                    <TableCell className="text-right">{product.sales}</TableCell>
                                    <TableCell className="text-right">{product.stock}</TableCell>
                                    <TableCell className="text-right">KES {(product.stock * product.cost).toLocaleString()}</TableCell>
                                </TableRow>
                            ))}
                        </TableBody>
                    </Table>
                </CardContent>
            </Card>
        </div>
    )
}
